{% set name = "azure-storage-queue" %}
{% set version = "2.0.0" %}
{% set sha256 = "d7645ff724b9bea9e43b62b99e15f7e90a7a9ee9811c1e6089754cac7bb00884" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - azure-common >=1.1.5
    - azure-storage-common >=1.3.0,<1.4.0

test:
  imports:
    - azure
    - azure.storage
    - azure.storage.queue

about:
  home: https://github.com/Azure/azure-storage-python
  license: Apache-2.0
  license_family: Apache
  license_file: {{ RECIPE_DIR }}/LICENSE.txt
  summary: 'Microsoft Azure Storage Queue Client Library for Python'

extra:
  recipe-maintainers:
    - xhochy
