travis:
  secure:
    BINSTAR_TOKEN: V4Aynuftb24Rl/i33rJMR9i/314YJ19/MOik7tw/xt6AFWoxMgENFAKnpvHN7B/stFeS/mwYUocCYsf82G7Buz5KDa+r4kbi6X1TUNp2ZFL5YAz8xLa+844mGSVkKSbLAFqWiYqfPoHDHWZvwfTT20pYJ1kdFU/l1k7KGimPSRH7sZpxIET5fglwPhZGkRXvOtV66WaUiktsj4eMObxid3MuAlXaORGU6AEHWJdE9pJKhonZB9FLTyZrwSzuNSuzQmt/05F9mZxjiq8QxT4o3PupWTBI7+UEj7pgeD07JvLkxKJlavPk11wuyJg37TfWQIKb0P7jjkKKaCfBtdeJZk93PDjEcrOamuu2iQHR93Qu+e3/Me+A4TvyWiSC6WUIGWRTa5iaUnkwEblzgeNin91UuoqZIjv8/pLOQwyEfLdPgES0caQCNBxDy+YQFj6UQciOYLWn03f1rQKqhM6fQ4DcPBPQWVCW4PkpLsXG9Ui2rowpGzzy9N76TZb6zt5fdWr/1QNMn13JX+3e2dqbzOsIHqfRiv1Dw/bIj0cB1VXW93YgrWfRyZqjUBmsqyo2/pnTQk0AlHiV2q+Jv7FeUyxf8IuAWKefp0WHzTqat6prhO9fkUXMtbeK6S/ZNvFVOE27UEPPvxmioOvQ3ShdTE8t2TAUf1NI4RktGWD6cxg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
