travis:
  secure:
    BINSTAR_TOKEN: zQMxEvnYHz4vWOGb8Xygcut7zox+4Y76UtnMSbsmMob8My1x58KckwP5xS03GYhRa9dc2nkHZjcVbPUzItr45ii8L4AqcH2EHgRFZmqCy4t9x+fy5GmnIuxK1gaBZF24x2IEaYFmg6sCeyUDzTiy2D+z/QxBResrhd8/W7PuMpEjwO4x9/uOOi4D/JVHytFR04LQX+CFQa8bz32kRzueR0BU6j84TWekq4FsA0fw8O20hwyKj+8OBuYf9nie51/zzcwGZsQUoh9YtNmp9Ku4N4LZViPErCFBi01Q9uYyafTI3bEQMArBJo7hRREKcAiToW2vAOWUfWCWXHMWAD/XcARzlVBfpQKWlLMxKUpE5hXdDGP8LIcmDIVc8BNIaQF7CRz6chcKx0V3cdD6WdQP5OqmJLZokLD3+iR52HGpAWjcI0JUOMnH+1CxKMxnjrmAqC/mVTYPtII1JVXaeFypyaah9rZtD9ryfGQpaGXXafHn8+wqP6xiIv7tmQeA/ySMsVFgZmv+ifdzufQd3F0ogOeiamT/ySlO34pjUhip0qRzIymnJ1RDR8ctSrCkHPG1TDtt2QVCMBH6MePYBg6nNSa86k21xjDVSIZ05EmLQrLILMBekC5U9MlNncKy/BxyNBiVW3Nb4woHWa54KbHMb5GZXOOV/uUBvpBRoYtFQAA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
